import type { Metadata } from 'next'
import { Roboto, Poppins } from 'next/font/google'

import './globals.css'
import { Providers } from './providers'

const roboto = Roboto({ subsets: ['latin'], weight: ['100', '300', '500', '700', '900'],  variable: '--font-roboto'})
const poppins = Poppins({ subsets: ['latin'], weight: ['100', '300', '500', '700', '900'], variable: '--font-poppins'})

export const metadata: Metadata = {
  title: 'GK Codez',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
          <Providers>
            {children}
          </Providers>
        </body>
    </html>
  )
}
